/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Disponible sólo cuando el restablecimiento local está habilitado. Elimina y vuelve a preparar exclusivamente la escuela de la sesión. */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateStudent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeStudentStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateNote"];
        post?: never;
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateGroup"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assignStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/attendance/{student}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateAttendance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateSessionStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voidPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["correctPayment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createDiscount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateOrderProgressBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateOrderProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            code?: string;
            fields?: {
                [key: string]: string;
            };
        };
        ResourceCreated: {
            /** Format: uuid */
            id: string;
            /** @default false */
            replayed: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        SessionResponse: {
            csrfToken: string;
        };
        StudentWrite: {
            firstNames: string;
            /** @description Admite un solo apellido. */
            lastNames: string;
            /** Format: date */
            birthDate: string;
            /** Format: uuid */
            gradeId: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            emailOwner?: "alumno" | "responsable" | "";
            primaryName: string;
            primaryRelation: string;
            primaryPhone: string;
            emergencyName: string;
            emergencyRelation: string;
            emergencyPhone: string;
            restrictions?: string;
            /** @description Consentimiento registrado en este entorno. */
            healthConsent?: boolean;
            /** Format: date */
            enrollmentDate: string;
            billingDay: number;
            version?: number;
        };
        StudentStatusWrite: {
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date */
            date: string;
            version: number;
        };
        NoteWrite: {
            /** Format: date */
            date: string;
            topic: string;
            text: string;
            /** Format: uuid */
            sessionId?: string | null;
            version?: number;
        };
        GroupWrite: {
            name: string;
            days: ("Lunes" | "Martes" | "Miércoles" | "Jueves" | "Viernes" | "Sábado")[];
            /** Format: time */
            start: string;
            /** Format: time */
            end: string;
            version?: number;
        };
        AssignmentWrite: {
            /** Format: uuid */
            studentId: string;
            /** Format: date */
            assignedFrom: string;
        };
        ParticipantWrite: {
            /** Format: uuid */
            studentId: string;
        };
        SessionWrite: {
            /** Format: uuid */
            groupId: string;
            /** Format: date */
            date: string;
            /** Format: time */
            start: string;
            /** Format: time */
            end: string;
        };
        SessionStatusWrite: {
            /** @enum {string} */
            status: "Cancelada" | "Reprogramada";
            version: number;
            /** Format: date */
            date?: string;
            /** Format: time */
            start?: string;
            /** Format: time */
            end?: string;
        };
        AttendanceWrite: {
            /** @enum {string} */
            status: "Presente" | "Ausente" | "Falta justificada" | "Sin registrar";
            observation?: string;
            version: number;
        };
        PaymentWrite: {
            /** Format: uuid */
            chargeId: string;
            amount: string;
            /** Format: date */
            date: string;
            /** @enum {string} */
            method?: "" | "Efectivo" | "Transferencia" | "Tarjeta" | "Otro";
            observation?: string;
            /** @description Obligatorio al corregir un pago existente. */
            reason?: string;
            version?: number;
        };
        VoidPaymentWrite: {
            reason: string;
            version: number;
        };
        DiscountWrite: {
            /** Format: uuid */
            studentId: string;
            /** @enum {string} */
            kind: "fixed" | "percentage";
            /** @description Centavos si es fijo; puntos base si es porcentaje (25 % = 2500). */
            value: number;
            reason: string;
            period?: string;
            recurring: boolean;
        };
        OrderItemWrite: {
            name: string;
            size?: string;
            quantity: number;
            price: string;
        };
        OrderWrite: {
            /** Format: uuid */
            studentId: string;
            /** Format: date */
            dueDate: string;
            items: components["schemas"]["OrderItemWrite"][];
        };
        OrderProgressWrite: {
            requested: boolean;
            received: number;
            delivered: number;
            cancelled: boolean;
            reason?: string;
            version: number;
        };
        OrderBulkProgressItem: {
            /** Format: uuid */
            id: string;
            version: number;
        };
        OrderBulkProgressWrite: {
            /** @enum {string} */
            mode: "receivePending" | "deliverReceived";
            items: components["schemas"]["OrderBulkProgressItem"][];
        };
    };
    responses: {
        /** @description No existe una sesión vigente. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description CSRF inválido o recurso de otra escuela. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La versión cambió o la operación contradice el estado actual. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Csrf: string;
        Idempotency: string;
        ResourceId: string;
        Version: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sesión iniciada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    currentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión vigente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión invalidada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Datos iniciales filtrados por la escuela de la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    resetDemo: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    confirm: "RESTABLECER";
                };
            };
        };
        responses: {
            /** @description Datos restablecidos y sesión invalidada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Restablecimiento deshabilitado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentWrite"];
            };
        };
        responses: {
            /** @description Reintento idempotente del alta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Alumno creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCreated"];
                };
            };
            /** @description Validación incorrecta */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentWrite"];
            };
        };
        responses: {
            /** @description Actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    changeStudentStatus: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentStatusWrite"];
            };
        };
        responses: {
            /** @description Estado actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteWrite"];
            };
        };
        responses: {
            /** @description Reintento idempotente del alta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nota creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteWrite"];
            };
        };
        responses: {
            /** @description Nota actualizada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    deleteNote: {
        parameters: {
            query: {
                version: number;
            };
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nota eliminada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupWrite"];
            };
        };
        responses: {
            /** @description Reintento idempotente del alta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Grupo creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupWrite"];
            };
        };
        responses: {
            /** @description Grupo actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignStudent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentWrite"];
            };
        };
        responses: {
            /** @description Asignación vigente */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionWrite"];
            };
        };
        responses: {
            /** @description Sesión creada o recuperada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inviteParticipant: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantWrite"];
            };
        };
        responses: {
            /** @description Participante presente sin duplicarse */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAttendance: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
                student: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceWrite"];
            };
        };
        responses: {
            /** @description Asistencia actualizada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateSessionStatus: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionStatusWrite"];
            };
        };
        responses: {
            /** @description Cancelación o reprogramación registrada conservando la sesión original */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWrite"];
            };
        };
        responses: {
            /** @description Reintento idempotente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pago registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Importe inválido o sobrepago */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    voidPayment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidPaymentWrite"];
            };
        };
        responses: {
            /** @description Pago anulado con historial */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    correctPayment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWrite"];
            };
        };
        responses: {
            /** @description Pago corregido y cambio conservado en historial */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    createDiscount: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscountWrite"];
            };
        };
        responses: {
            /** @description Descuento futuro registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datos o alumno inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderWrite"];
            };
        };
        responses: {
            /** @description Reintento idempotente del alta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pedido y cobros por artículo creados atómicamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateOrderProgressBulk: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
                "Idempotency-Key": components["parameters"]["Idempotency"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderBulkProgressWrite"];
            };
        };
        responses: {
            /** @description Todos los artículos activos avanzaron atómicamente o el reintento ya había sido aplicado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Modo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pedido no encontrado en la escuela */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateOrderProgress: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["Csrf"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderProgressWrite"];
            };
        };
        responses: {
            /** @description Avance actualizado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
}
